<?php

require_once dirname(__FILE__) . '/../../classe/caffiche_graphe.php';

/**
 * Test class for CAffiche_graphe.
 * Generated by PHPUnit on 2011-09-11 at 20:44:31.
 */
class CAffiche_grapheTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CAffiche_graphe
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CAffiche_graphe;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testConstruct().
     */
    public function testConstruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDestruct().
     */
    public function testDestruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testPurge_images().
     */
    public function testPurge_images() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRecherche_disk().
     */
    public function testRecherche_disk() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
