<?php

require_once dirname(__FILE__) . '/../../classe/cihm.php';

/**
 * Test class for CIhm.
 * Generated by PHPUnit on 2011-09-11 at 22:57:39.
 */
class CIhmTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CIhm
     */
    protected $object;

    protected $t_in = array('path'=>'/myhome',
                            'title'=>'Menu de test',
                            'analytic'=>'UA-123123-1',
                            'menu'=>'The menu',
                            'agent'=>'xcx palm sdfsdf'
                            );

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CIhm($this->t_in['path'],
                                $this->t_in['title'],
                                $this->t_in['analytic'],
                                $this->t_in['agent']
                                 );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testDestruct().
     */
    public function testDestruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGet_tetiere().
     */
    public function testGet_tetiere() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGet_header().
     */
    public function testGet_header() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testFooter().
     */
    public function testFooter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGet_type_navigateur().
     */
    public function testGet_type_navigateur() {
        // Remove the following lines when you implement this test.
        $this->assertEquals( "Mobile",
                $this->object->get_type_navigateur()
        );
    }

}

?>
