<?php

require_once dirname(__FILE__) . '/../../classe/cutilitaire.php';

/**
 * Test class for CUtilitaire.
 * Generated by PHPUnit on 2011-09-11 at 21:34:39.
 */
class CUtilitaireTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CUtilitaire
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CUtilitaire;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * Generated from @assert ("rel_mytable_1","rel_") == "mytable 1".
     */
    public function testModule_short() {
        $this->assertEquals(
                "mytable 1"
                ,
                CUtilitaire::module_short("rel_mytable_1", "rel_")
        );
    }

    /**
     * Generated from @assert ("rel_mytable_1","") == "rel mytable 1".
     */
    public function testModule_short2() {
        $this->assertEquals(
                "rel mytable 1"
                ,
                CUtilitaire::module_short("rel_mytable_1", "")
        );
    }

    /**
     * Generated from @assert ("rel_mytable_1","tot") == "rel mytable 1".
     */
    public function testModule_short3() {
        $this->assertEquals(
                "rel mytable 1"
                ,
                CUtilitaire::module_short("rel_mytable_1", "tot")
        );
    }

    /**
     * Generated from @assert ("","") == "".
     */
    public function testModule_short4() {
        $this->assertEquals(
                ""
                ,
                CUtilitaire::module_short("", "")
        );
    }

    /**
     * Generated from @assert ("","rel_") == "".
     */
    public function testModule_short5() {
        $this->assertEquals(
                ""
                ,
                CUtilitaire::module_short("", "rel_")
        );
    }

    /**
     * Generated from @assert ("2011-05-11") == "11/05/2011".
     */
    public function testDate_iso2fr() {
        $this->assertEquals(
                "11/05/2011"
                ,
                CUtilitaire::date_iso2fr("2011-05-11")
        );
    }

    /**
     * Generated from @assert () == "".
     */
    public function testDate_iso2fr2() {
        $this->assertEquals(
                ""
                ,
                CUtilitaire::date_iso2fr()
        );
    }

    /**
     * Generated from @assert ("2011-5-11") == "2011-5-11".
     */
    public function testDate_iso2fr3() {
        $this->assertEquals(
                "2011-5-11"
                ,
                CUtilitaire::date_iso2fr("2011-5-11")
        );
    }

    /**
     * Generated from @assert ("11/05/11") == "11/05/11".
     */
    public function testDate_iso2fr4() {
        $this->assertEquals(
                "11/05/11"
                ,
                CUtilitaire::date_iso2fr("11/05/11")
        );
    }

}

?>
